### ISSUE TITLE
Install fails on Atom 1.36 at windows

### ISSUE THREAD

**Issue by bmxp** [bluec0re/atom-rst-preview-docutils#7]
```
Installing “atom-rst-preview-docutils@1.0.0” failed.Hide output…

> oniguruma@6.2.1 install C:\<privacy protected>\AppData\Local\Temp\apm-install-dir-119314-8600-aq83i.hpslvs\node_modules\atom-rst-preview-docutils\node_modules\oniguruma
> node-gyp rebuild


C:\<privacy protected>\AppData\Local\Temp\apm-install-dir-119314-8600-aq83i.hpslvs\node_modules\atom-rst-preview-docutils\node_modules\oniguruma>if not defined npm_config_node_gyp (node "C:\<privacy protected>\AppData\Local\atom\app-1.36.0\resources\app\apm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\<privacy protected>\AppData\Local\atom\app-1.36.0\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 

npm WARN deprecated coffee-script@1.9.0: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\<privacy protected>\\AppData\\Local\\atom\\app-1.36.0\\resources\\app\\apm\\bin\\node.exe',
gyp verb cli   'C:\\<privacy protected>\\AppData\\Local\\atom\\app-1.36.0\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild' ]
gyp info using node-gyp@3.4.0
gyp info using node@8.9.3 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\<privacy protected>\AppData\Local\atom\app-1.36.0\resources\app\apm\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\<privacy protected>\AppData\Local\atom\app-1.36.0\resources\app\apm\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\<privacy protected>\AppData\Local\atom\app-1.36.0\resources\app\apm\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\<privacy protected>\AppData\Local\atom\app-1.36.0\resources\app\apm\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\<privacy protected>\AppData\Local\atom\app-1.36.0\resources\app\apm\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\<privacy protected>\AppData\Local\atom\app-1.36.0\resources\app\apm\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\<privacy protected>\AppData\Local\atom\app-1.36.0\resources\app\apm\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\<privacy protected>\AppData\Local\atom\app-1.36.0\resources\app\apm\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\<privacy protected>\AppData\Local\atom\app-1.36.0\resources\app\apm\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\<privacy protected>\AppData\Local\atom\app-1.36.0\resources\app\apm\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\<privacy protected>\AppData\Local\atom\app-1.36.0\resources\app\apm\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\<privacy protected>\AppData\Local\atom\app-1.36.0\resources\app\apm\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21) code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\Python\python.EXE
gyp verb check python version `C:\Python\python.EXE -c "import platform; print(platform.python_version());"` returned: "3.6.8\r\n"
gyp ERR! configure error 
gyp ERR! stack Error: Python executable "C:\Python\python.EXE" is v3.6.8, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (C:\<privacy protected>\AppData\Local\atom\app-1.36.0\resources\app\apm\node_modules\node-gyp\lib\configure.js:454:14)
gyp ERR! stack     at C:\<privacy protected>\AppData\Local\atom\app-1.36.0\resources\app\apm\node_modules\node-gyp\lib\configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:267:7)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:346:11)
gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! stack     at Socket.emit (events.js:211:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:554:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\<privacy protected>\\AppData\\Local\\atom\\app-1.36.0\\resources\\app\\apm\\bin\\node.exe" "C:\\<privacy protected>\\AppData\\Local\\atom\\app-1.36.0\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\<privacy protected>\AppData\Local\Temp\apm-install-dir-119314-8600-aq83i.hpslvs\node_modules\atom-rst-preview-docutils\node_modules\oniguruma
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\<privacy protected>\AppData\Local\Temp\apm-install-dir-119314-8600-aq83i.hpslvs\package.json'
npm WARN apm-install-dir-119314-8600-aq83i.hpslvs No description
npm WARN apm-install-dir-119314-8600-aq83i.hpslvs No repository field.
npm WARN apm-install-dir-119314-8600-aq83i.hpslvs No README data
npm WARN apm-install-dir-119314-8600-aq83i.hpslvs No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! oniguruma@6.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the oniguruma@6.2.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\<privacy protected>\.atom\.apm\_logs\2019-04-14T09_22_16_788Z-debug.log
```

**Comment by om-design** [comment]
very similar experience
