### ISSUE TITLE
Install fails on Atom on macOS

### ISSUE THREAD

**Issue by userlerueda** [bluec0re/atom-rst-preview-docutils#9]
```
npm WARN deprecated coffee-script@1.9.0: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
gyp ERR! configure error
gyp ERR! stack Error: Python executable "/Applications/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh" is v3.7.7, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at PythonFinder.failPythonVersion (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:501:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:483:14)
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:282:7)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:961:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:380:11)
gyp ERR! stack     at Socket.emit (events.js:182:13)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:596:12)
gyp ERR! System Darwin 19.4.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/1v/mzkrj77j2rn7lqjp9z91f4d00000gp/T/apm-install-dir-12047-79671-dirviw.7s37/node_modules/atom-rst-preview-docutils/node_modules/oniguruma
gyp ERR! node -v v10.2.1
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/1v/mzkrj77j2rn7lqjp9z91f4d00000gp/T/apm-install-dir-12047-79671-dirviw.7s37/package.json'
npm WARN apm-install-dir-12047-79671-dirviw.7s37 No description
npm WARN apm-install-dir-12047-79671-dirviw.7s37 No repository field.
npm WARN apm-install-dir-12047-79671-dirviw.7s37 No README data
npm WARN apm-install-dir-12047-79671-dirviw.7s37 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! oniguruma@6.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the oniguruma@6.2.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by chapuzzo** [comment]
I found a solution.
In my case I installed anaconda-navigator recently and it added conda stuff to my bash profile. I disabled `auto_activate_base`, (`conda deactivate` also works) started atom from command line and install succeeded.
Hope it suits you
